### ISSUE TITLE
Broken on Fabric 2.0 

### ISSUE THREAD

**Issue by panthar1** [EffEPi/fabric.curvedText#43]
Hello,

I see you updated the code to work with fabric 2.0 beta, and it works with fabric beta, however, the newest master version does not work:

08:32:01.885 fabric.curvedText.js:39 Uncaught TypeError: Cannot set property 'backgroundColor' of undefined
    at fabric.curvedText.js:39
    at fabric.curvedText.js:566
08:32:01.928 jquery-git.js:3873 jQuery.Deferred exception: fabric.CurvedText is not a constructor TypeError: fabric.CurvedText is not a constructor
    at HTMLDocument.<anonymous> (file:///C:/wamp/www/CurvedTest/index.html:46:20)
    at mightThrow (http://code.jquery.com/jquery-git.js:3589:29)
    at process (http://code.jquery.com/jquery-git.js:3657:12) undefined
jQuery.Deferred.exceptionHook @ jquery-git.js:3873
08:32:01.930 jquery-git.js:3882 Uncaught TypeError: fabric.CurvedText is not a constructor
    at HTMLDocument.<anonymous> (index.html:46)
    at mightThrow (jquery-git.js:3589)
    at process (jquery-git.js:3657)

All the best

**Comment by JugnuPathak** [comment]
Also not compatible with latest version of fabric.js 2.2.2.
